# Generated by Django 5.1.3 on 2024-12-01 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carad',
            name='city',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='carad',
            name='country',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='carad',
            name='year',
            field=models.PositiveIntegerField(),
        ),
    ]
